# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  install-deps:
    docker:
      - image: node:16.13.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
  build:
    docker:
      - image: node:16.13.0
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # fallback to latest cache
            - dependencies-
      - run:
          name: Build
          command: yarn build
      - save_cache:
          paths:
            - dist
          key: dist-{{ .Revision }}
  publish:
    docker:
      - image: node:16.13.0
    resource_class: small
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2d:a9:2f:58:bd:35:f8:65:a2:16:d1:07:e3:ec:97:c8"
      - run:
          name: Publish
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ams.eee09@gmail.com"
            git config user.name "Asif Mahmud Shimon"
      - restore_cache:
          keys:
            - dist-{{ .Revision }}
            # fallback to latest cache
            - dist-
      - run:
          name: Skip jekyll
          command: touch dist/.nojekyll
      - run:
          name: Deploy to github pages
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist dist

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  github-page:
    jobs:
      - install-deps:
          filters:
            branches:
              only: master
      - build:
          requires:
            - install-deps
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
